// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: base.proto
// Protobuf C++ Version: 5.29.3

#include "base.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace base {

inline constexpr Rect::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : left_{0},
        top_{0},
        right_{0},
        bottom_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Rect::Rect(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct RectDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RectDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RectDefaultTypeInternal() {}
  union {
    Rect _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RectDefaultTypeInternal _Rect_default_instance_;

inline constexpr Point::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : left_{0},
        top_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Point::Point(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PointDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PointDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PointDefaultTypeInternal() {}
  union {
    Point _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PointDefaultTypeInternal _Point_default_instance_;

inline constexpr IntRect::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : left_{0},
        top_{0},
        right_{0},
        bottom_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR IntRect::IntRect(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct IntRectDefaultTypeInternal {
  PROTOBUF_CONSTEXPR IntRectDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~IntRectDefaultTypeInternal() {}
  union {
    IntRect _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 IntRectDefaultTypeInternal _IntRect_default_instance_;

inline constexpr IntPoint::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : left_{0},
        top_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR IntPoint::IntPoint(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct IntPointDefaultTypeInternal {
  PROTOBUF_CONSTEXPR IntPointDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~IntPointDefaultTypeInternal() {}
  union {
    IntPoint _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 IntPointDefaultTypeInternal _IntPoint_default_instance_;
}  // namespace base
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_base_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_base_2eproto = nullptr;
const ::uint32_t
    TableStruct_base_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::base::IntRect, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::base::IntRect, _impl_.left_),
        PROTOBUF_FIELD_OFFSET(::base::IntRect, _impl_.top_),
        PROTOBUF_FIELD_OFFSET(::base::IntRect, _impl_.right_),
        PROTOBUF_FIELD_OFFSET(::base::IntRect, _impl_.bottom_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::base::Rect, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::base::Rect, _impl_.left_),
        PROTOBUF_FIELD_OFFSET(::base::Rect, _impl_.top_),
        PROTOBUF_FIELD_OFFSET(::base::Rect, _impl_.right_),
        PROTOBUF_FIELD_OFFSET(::base::Rect, _impl_.bottom_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::base::IntPoint, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::base::IntPoint, _impl_.left_),
        PROTOBUF_FIELD_OFFSET(::base::IntPoint, _impl_.top_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::base::Point, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::base::Point, _impl_.left_),
        PROTOBUF_FIELD_OFFSET(::base::Point, _impl_.top_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::base::IntRect)},
        {12, -1, -1, sizeof(::base::Rect)},
        {24, -1, -1, sizeof(::base::IntPoint)},
        {34, -1, -1, sizeof(::base::Point)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::base::_IntRect_default_instance_._instance,
    &::base::_Rect_default_instance_._instance,
    &::base::_IntPoint_default_instance_._instance,
    &::base::_Point_default_instance_._instance,
};
const char descriptor_table_protodef_base_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\nbase.proto\022\004base\"C\n\007IntRect\022\014\n\004left\030\001 "
    "\001(\005\022\013\n\003top\030\002 \001(\005\022\r\n\005right\030\003 \001(\005\022\016\n\006botto"
    "m\030\004 \001(\005\"@\n\004Rect\022\014\n\004left\030\001 \001(\001\022\013\n\003top\030\002 \001"
    "(\001\022\r\n\005right\030\003 \001(\001\022\016\n\006bottom\030\004 \001(\001\"%\n\010Int"
    "Point\022\014\n\004left\030\001 \001(\005\022\013\n\003top\030\002 \001(\005\"\"\n\005Poin"
    "t\022\014\n\004left\030\001 \001(\001\022\013\n\003top\030\002 \001(\001b\006proto3"
};
static ::absl::once_flag descriptor_table_base_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_base_2eproto = {
    false,
    false,
    236,
    descriptor_table_protodef_base_2eproto,
    "base.proto",
    &descriptor_table_base_2eproto_once,
    nullptr,
    0,
    4,
    schemas,
    file_default_instances,
    TableStruct_base_2eproto::offsets,
    file_level_enum_descriptors_base_2eproto,
    file_level_service_descriptors_base_2eproto,
};
namespace base {
// ===================================================================

class IntRect::_Internal {
 public:
};

IntRect::IntRect(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:base.IntRect)
}
IntRect::IntRect(
    ::google::protobuf::Arena* arena, const IntRect& from)
    : IntRect(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE IntRect::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void IntRect::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, left_),
           0,
           offsetof(Impl_, bottom_) -
               offsetof(Impl_, left_) +
               sizeof(Impl_::bottom_));
}
IntRect::~IntRect() {
  // @@protoc_insertion_point(destructor:base.IntRect)
  SharedDtor(*this);
}
inline void IntRect::SharedDtor(MessageLite& self) {
  IntRect& this_ = static_cast<IntRect&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* IntRect::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) IntRect(arena);
}
constexpr auto IntRect::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(IntRect),
                                            alignof(IntRect));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull IntRect::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_IntRect_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &IntRect::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<IntRect>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &IntRect::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<IntRect>(), &IntRect::ByteSizeLong,
            &IntRect::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(IntRect, _impl_._cached_size_),
        false,
    },
    &IntRect::kDescriptorMethods,
    &descriptor_table_base_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* IntRect::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 0, 2> IntRect::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::base::IntRect>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 bottom = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(IntRect, _impl_.bottom_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(IntRect, _impl_.bottom_)}},
    // int32 left = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(IntRect, _impl_.left_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(IntRect, _impl_.left_)}},
    // int32 top = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(IntRect, _impl_.top_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(IntRect, _impl_.top_)}},
    // int32 right = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(IntRect, _impl_.right_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(IntRect, _impl_.right_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 left = 1;
    {PROTOBUF_FIELD_OFFSET(IntRect, _impl_.left_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 top = 2;
    {PROTOBUF_FIELD_OFFSET(IntRect, _impl_.top_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 right = 3;
    {PROTOBUF_FIELD_OFFSET(IntRect, _impl_.right_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 bottom = 4;
    {PROTOBUF_FIELD_OFFSET(IntRect, _impl_.bottom_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void IntRect::Clear() {
// @@protoc_insertion_point(message_clear_start:base.IntRect)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.left_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.bottom_) -
      reinterpret_cast<char*>(&_impl_.left_)) + sizeof(_impl_.bottom_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* IntRect::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const IntRect& this_ = static_cast<const IntRect&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* IntRect::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const IntRect& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:base.IntRect)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 left = 1;
          if (this_._internal_left() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_left(), target);
          }

          // int32 top = 2;
          if (this_._internal_top() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<2>(
                    stream, this_._internal_top(), target);
          }

          // int32 right = 3;
          if (this_._internal_right() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<3>(
                    stream, this_._internal_right(), target);
          }

          // int32 bottom = 4;
          if (this_._internal_bottom() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<4>(
                    stream, this_._internal_bottom(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:base.IntRect)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t IntRect::ByteSizeLong(const MessageLite& base) {
          const IntRect& this_ = static_cast<const IntRect&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t IntRect::ByteSizeLong() const {
          const IntRect& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:base.IntRect)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // int32 left = 1;
            if (this_._internal_left() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_left());
            }
            // int32 top = 2;
            if (this_._internal_top() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_top());
            }
            // int32 right = 3;
            if (this_._internal_right() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_right());
            }
            // int32 bottom = 4;
            if (this_._internal_bottom() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_bottom());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void IntRect::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<IntRect*>(&to_msg);
  auto& from = static_cast<const IntRect&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:base.IntRect)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_left() != 0) {
    _this->_impl_.left_ = from._impl_.left_;
  }
  if (from._internal_top() != 0) {
    _this->_impl_.top_ = from._impl_.top_;
  }
  if (from._internal_right() != 0) {
    _this->_impl_.right_ = from._impl_.right_;
  }
  if (from._internal_bottom() != 0) {
    _this->_impl_.bottom_ = from._impl_.bottom_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void IntRect::CopyFrom(const IntRect& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:base.IntRect)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void IntRect::InternalSwap(IntRect* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(IntRect, _impl_.bottom_)
      + sizeof(IntRect::_impl_.bottom_)
      - PROTOBUF_FIELD_OFFSET(IntRect, _impl_.left_)>(
          reinterpret_cast<char*>(&_impl_.left_),
          reinterpret_cast<char*>(&other->_impl_.left_));
}

::google::protobuf::Metadata IntRect::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Rect::_Internal {
 public:
};

Rect::Rect(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:base.Rect)
}
Rect::Rect(
    ::google::protobuf::Arena* arena, const Rect& from)
    : Rect(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE Rect::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void Rect::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, left_),
           0,
           offsetof(Impl_, bottom_) -
               offsetof(Impl_, left_) +
               sizeof(Impl_::bottom_));
}
Rect::~Rect() {
  // @@protoc_insertion_point(destructor:base.Rect)
  SharedDtor(*this);
}
inline void Rect::SharedDtor(MessageLite& self) {
  Rect& this_ = static_cast<Rect&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* Rect::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) Rect(arena);
}
constexpr auto Rect::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(Rect),
                                            alignof(Rect));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull Rect::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_Rect_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &Rect::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<Rect>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &Rect::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<Rect>(), &Rect::ByteSizeLong,
            &Rect::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(Rect, _impl_._cached_size_),
        false,
    },
    &Rect::kDescriptorMethods,
    &descriptor_table_base_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* Rect::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 0, 2> Rect::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::base::Rect>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // double bottom = 4;
    {::_pbi::TcParser::FastF64S1,
     {33, 63, 0, PROTOBUF_FIELD_OFFSET(Rect, _impl_.bottom_)}},
    // double left = 1;
    {::_pbi::TcParser::FastF64S1,
     {9, 63, 0, PROTOBUF_FIELD_OFFSET(Rect, _impl_.left_)}},
    // double top = 2;
    {::_pbi::TcParser::FastF64S1,
     {17, 63, 0, PROTOBUF_FIELD_OFFSET(Rect, _impl_.top_)}},
    // double right = 3;
    {::_pbi::TcParser::FastF64S1,
     {25, 63, 0, PROTOBUF_FIELD_OFFSET(Rect, _impl_.right_)}},
  }}, {{
    65535, 65535
  }}, {{
    // double left = 1;
    {PROTOBUF_FIELD_OFFSET(Rect, _impl_.left_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // double top = 2;
    {PROTOBUF_FIELD_OFFSET(Rect, _impl_.top_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // double right = 3;
    {PROTOBUF_FIELD_OFFSET(Rect, _impl_.right_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // double bottom = 4;
    {PROTOBUF_FIELD_OFFSET(Rect, _impl_.bottom_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void Rect::Clear() {
// @@protoc_insertion_point(message_clear_start:base.Rect)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.left_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.bottom_) -
      reinterpret_cast<char*>(&_impl_.left_)) + sizeof(_impl_.bottom_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Rect::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Rect& this_ = static_cast<const Rect&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Rect::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Rect& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:base.Rect)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // double left = 1;
          if (::absl::bit_cast<::uint64_t>(this_._internal_left()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                1, this_._internal_left(), target);
          }

          // double top = 2;
          if (::absl::bit_cast<::uint64_t>(this_._internal_top()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                2, this_._internal_top(), target);
          }

          // double right = 3;
          if (::absl::bit_cast<::uint64_t>(this_._internal_right()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                3, this_._internal_right(), target);
          }

          // double bottom = 4;
          if (::absl::bit_cast<::uint64_t>(this_._internal_bottom()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                4, this_._internal_bottom(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:base.Rect)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Rect::ByteSizeLong(const MessageLite& base) {
          const Rect& this_ = static_cast<const Rect&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Rect::ByteSizeLong() const {
          const Rect& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:base.Rect)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // double left = 1;
            if (::absl::bit_cast<::uint64_t>(this_._internal_left()) != 0) {
              total_size += 9;
            }
            // double top = 2;
            if (::absl::bit_cast<::uint64_t>(this_._internal_top()) != 0) {
              total_size += 9;
            }
            // double right = 3;
            if (::absl::bit_cast<::uint64_t>(this_._internal_right()) != 0) {
              total_size += 9;
            }
            // double bottom = 4;
            if (::absl::bit_cast<::uint64_t>(this_._internal_bottom()) != 0) {
              total_size += 9;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void Rect::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Rect*>(&to_msg);
  auto& from = static_cast<const Rect&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:base.Rect)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (::absl::bit_cast<::uint64_t>(from._internal_left()) != 0) {
    _this->_impl_.left_ = from._impl_.left_;
  }
  if (::absl::bit_cast<::uint64_t>(from._internal_top()) != 0) {
    _this->_impl_.top_ = from._impl_.top_;
  }
  if (::absl::bit_cast<::uint64_t>(from._internal_right()) != 0) {
    _this->_impl_.right_ = from._impl_.right_;
  }
  if (::absl::bit_cast<::uint64_t>(from._internal_bottom()) != 0) {
    _this->_impl_.bottom_ = from._impl_.bottom_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Rect::CopyFrom(const Rect& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:base.Rect)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Rect::InternalSwap(Rect* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Rect, _impl_.bottom_)
      + sizeof(Rect::_impl_.bottom_)
      - PROTOBUF_FIELD_OFFSET(Rect, _impl_.left_)>(
          reinterpret_cast<char*>(&_impl_.left_),
          reinterpret_cast<char*>(&other->_impl_.left_));
}

::google::protobuf::Metadata Rect::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class IntPoint::_Internal {
 public:
};

IntPoint::IntPoint(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:base.IntPoint)
}
IntPoint::IntPoint(
    ::google::protobuf::Arena* arena, const IntPoint& from)
    : IntPoint(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE IntPoint::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void IntPoint::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, left_),
           0,
           offsetof(Impl_, top_) -
               offsetof(Impl_, left_) +
               sizeof(Impl_::top_));
}
IntPoint::~IntPoint() {
  // @@protoc_insertion_point(destructor:base.IntPoint)
  SharedDtor(*this);
}
inline void IntPoint::SharedDtor(MessageLite& self) {
  IntPoint& this_ = static_cast<IntPoint&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* IntPoint::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) IntPoint(arena);
}
constexpr auto IntPoint::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(IntPoint),
                                            alignof(IntPoint));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull IntPoint::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_IntPoint_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &IntPoint::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<IntPoint>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &IntPoint::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<IntPoint>(), &IntPoint::ByteSizeLong,
            &IntPoint::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(IntPoint, _impl_._cached_size_),
        false,
    },
    &IntPoint::kDescriptorMethods,
    &descriptor_table_base_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* IntPoint::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> IntPoint::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::base::IntPoint>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 top = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(IntPoint, _impl_.top_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(IntPoint, _impl_.top_)}},
    // int32 left = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(IntPoint, _impl_.left_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(IntPoint, _impl_.left_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 left = 1;
    {PROTOBUF_FIELD_OFFSET(IntPoint, _impl_.left_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 top = 2;
    {PROTOBUF_FIELD_OFFSET(IntPoint, _impl_.top_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void IntPoint::Clear() {
// @@protoc_insertion_point(message_clear_start:base.IntPoint)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.left_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.top_) -
      reinterpret_cast<char*>(&_impl_.left_)) + sizeof(_impl_.top_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* IntPoint::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const IntPoint& this_ = static_cast<const IntPoint&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* IntPoint::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const IntPoint& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:base.IntPoint)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 left = 1;
          if (this_._internal_left() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_left(), target);
          }

          // int32 top = 2;
          if (this_._internal_top() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<2>(
                    stream, this_._internal_top(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:base.IntPoint)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t IntPoint::ByteSizeLong(const MessageLite& base) {
          const IntPoint& this_ = static_cast<const IntPoint&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t IntPoint::ByteSizeLong() const {
          const IntPoint& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:base.IntPoint)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // int32 left = 1;
            if (this_._internal_left() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_left());
            }
            // int32 top = 2;
            if (this_._internal_top() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_top());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void IntPoint::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<IntPoint*>(&to_msg);
  auto& from = static_cast<const IntPoint&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:base.IntPoint)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_left() != 0) {
    _this->_impl_.left_ = from._impl_.left_;
  }
  if (from._internal_top() != 0) {
    _this->_impl_.top_ = from._impl_.top_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void IntPoint::CopyFrom(const IntPoint& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:base.IntPoint)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void IntPoint::InternalSwap(IntPoint* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(IntPoint, _impl_.top_)
      + sizeof(IntPoint::_impl_.top_)
      - PROTOBUF_FIELD_OFFSET(IntPoint, _impl_.left_)>(
          reinterpret_cast<char*>(&_impl_.left_),
          reinterpret_cast<char*>(&other->_impl_.left_));
}

::google::protobuf::Metadata IntPoint::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Point::_Internal {
 public:
};

Point::Point(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:base.Point)
}
Point::Point(
    ::google::protobuf::Arena* arena, const Point& from)
    : Point(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE Point::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void Point::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, left_),
           0,
           offsetof(Impl_, top_) -
               offsetof(Impl_, left_) +
               sizeof(Impl_::top_));
}
Point::~Point() {
  // @@protoc_insertion_point(destructor:base.Point)
  SharedDtor(*this);
}
inline void Point::SharedDtor(MessageLite& self) {
  Point& this_ = static_cast<Point&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* Point::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) Point(arena);
}
constexpr auto Point::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(Point),
                                            alignof(Point));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull Point::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_Point_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &Point::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<Point>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &Point::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<Point>(), &Point::ByteSizeLong,
            &Point::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(Point, _impl_._cached_size_),
        false,
    },
    &Point::kDescriptorMethods,
    &descriptor_table_base_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* Point::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> Point::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::base::Point>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // double top = 2;
    {::_pbi::TcParser::FastF64S1,
     {17, 63, 0, PROTOBUF_FIELD_OFFSET(Point, _impl_.top_)}},
    // double left = 1;
    {::_pbi::TcParser::FastF64S1,
     {9, 63, 0, PROTOBUF_FIELD_OFFSET(Point, _impl_.left_)}},
  }}, {{
    65535, 65535
  }}, {{
    // double left = 1;
    {PROTOBUF_FIELD_OFFSET(Point, _impl_.left_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // double top = 2;
    {PROTOBUF_FIELD_OFFSET(Point, _impl_.top_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void Point::Clear() {
// @@protoc_insertion_point(message_clear_start:base.Point)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.left_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.top_) -
      reinterpret_cast<char*>(&_impl_.left_)) + sizeof(_impl_.top_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Point::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Point& this_ = static_cast<const Point&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Point::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Point& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:base.Point)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // double left = 1;
          if (::absl::bit_cast<::uint64_t>(this_._internal_left()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                1, this_._internal_left(), target);
          }

          // double top = 2;
          if (::absl::bit_cast<::uint64_t>(this_._internal_top()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                2, this_._internal_top(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:base.Point)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Point::ByteSizeLong(const MessageLite& base) {
          const Point& this_ = static_cast<const Point&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Point::ByteSizeLong() const {
          const Point& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:base.Point)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // double left = 1;
            if (::absl::bit_cast<::uint64_t>(this_._internal_left()) != 0) {
              total_size += 9;
            }
            // double top = 2;
            if (::absl::bit_cast<::uint64_t>(this_._internal_top()) != 0) {
              total_size += 9;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void Point::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Point*>(&to_msg);
  auto& from = static_cast<const Point&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:base.Point)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (::absl::bit_cast<::uint64_t>(from._internal_left()) != 0) {
    _this->_impl_.left_ = from._impl_.left_;
  }
  if (::absl::bit_cast<::uint64_t>(from._internal_top()) != 0) {
    _this->_impl_.top_ = from._impl_.top_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Point::CopyFrom(const Point& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:base.Point)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Point::InternalSwap(Point* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Point, _impl_.top_)
      + sizeof(Point::_impl_.top_)
      - PROTOBUF_FIELD_OFFSET(Point, _impl_.left_)>(
          reinterpret_cast<char*>(&_impl_.left_),
          reinterpret_cast<char*>(&other->_impl_.left_));
}

::google::protobuf::Metadata Point::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace base
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_base_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
