// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: camera_config.proto
// Protobuf C++ Version: 5.29.3

#include "camera_config.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace camera_config {

inline constexpr DirectoryCameraConfig::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : directory_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        image_extension_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        loop_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR DirectoryCameraConfig::DirectoryCameraConfig(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct DirectoryCameraConfigDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DirectoryCameraConfigDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~DirectoryCameraConfigDefaultTypeInternal() {}
  union {
    DirectoryCameraConfig _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DirectoryCameraConfigDefaultTypeInternal _DirectoryCameraConfig_default_instance_;

inline constexpr CameraConfig::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        serial_number_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        type_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        roi_{nullptr},
        virtual_folder_{nullptr},
        id_{0},
        frame_count_{0},
        exposure_time_{0},
        frame_rate_{0},
        gain_{0},
        image_node_number_{0},
        image_type_{0},
        reverse_image_{0},
        trigger_type_{0} {}

template <typename>
PROTOBUF_CONSTEXPR CameraConfig::CameraConfig(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CameraConfigDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CameraConfigDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CameraConfigDefaultTypeInternal() {}
  union {
    CameraConfig _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CameraConfigDefaultTypeInternal _CameraConfig_default_instance_;

inline constexpr Cameras::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : camera_configs_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Cameras::Cameras(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CamerasDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CamerasDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CamerasDefaultTypeInternal() {}
  union {
    Cameras _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CamerasDefaultTypeInternal _Cameras_default_instance_;
}  // namespace camera_config
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_camera_5fconfig_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_camera_5fconfig_2eproto = nullptr;
const ::uint32_t
    TableStruct_camera_5fconfig_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::camera_config::CameraConfig, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::camera_config::CameraConfig, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::camera_config::CameraConfig, _impl_.id_),
        PROTOBUF_FIELD_OFFSET(::camera_config::CameraConfig, _impl_.name_),
        PROTOBUF_FIELD_OFFSET(::camera_config::CameraConfig, _impl_.serial_number_),
        PROTOBUF_FIELD_OFFSET(::camera_config::CameraConfig, _impl_.type_),
        PROTOBUF_FIELD_OFFSET(::camera_config::CameraConfig, _impl_.exposure_time_),
        PROTOBUF_FIELD_OFFSET(::camera_config::CameraConfig, _impl_.frame_count_),
        PROTOBUF_FIELD_OFFSET(::camera_config::CameraConfig, _impl_.frame_rate_),
        PROTOBUF_FIELD_OFFSET(::camera_config::CameraConfig, _impl_.gain_),
        PROTOBUF_FIELD_OFFSET(::camera_config::CameraConfig, _impl_.image_node_number_),
        PROTOBUF_FIELD_OFFSET(::camera_config::CameraConfig, _impl_.image_type_),
        PROTOBUF_FIELD_OFFSET(::camera_config::CameraConfig, _impl_.roi_),
        PROTOBUF_FIELD_OFFSET(::camera_config::CameraConfig, _impl_.reverse_image_),
        PROTOBUF_FIELD_OFFSET(::camera_config::CameraConfig, _impl_.trigger_type_),
        PROTOBUF_FIELD_OFFSET(::camera_config::CameraConfig, _impl_.virtual_folder_),
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        0,
        2,
        ~0u,
        1,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::camera_config::DirectoryCameraConfig, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::camera_config::DirectoryCameraConfig, _impl_.directory_),
        PROTOBUF_FIELD_OFFSET(::camera_config::DirectoryCameraConfig, _impl_.image_extension_),
        PROTOBUF_FIELD_OFFSET(::camera_config::DirectoryCameraConfig, _impl_.loop_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::camera_config::Cameras, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::camera_config::Cameras, _impl_.camera_configs_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 22, -1, sizeof(::camera_config::CameraConfig)},
        {36, -1, -1, sizeof(::camera_config::DirectoryCameraConfig)},
        {47, -1, -1, sizeof(::camera_config::Cameras)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::camera_config::_CameraConfig_default_instance_._instance,
    &::camera_config::_DirectoryCameraConfig_default_instance_._instance,
    &::camera_config::_Cameras_default_instance_._instance,
};
const char descriptor_table_protodef_camera_5fconfig_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\023camera_config.proto\022\rcamera_config\032\nba"
    "se.proto\"\215\003\n\014CameraConfig\022\n\n\002id\030\001 \001(\005\022\014\n"
    "\004name\030\002 \001(\t\022\025\n\rserial_number\030\003 \001(\t\022\014\n\004ty"
    "pe\030\004 \001(\t\022\025\n\rexposure_time\030\005 \001(\001\022\023\n\013frame"
    "_count\030\006 \001(\005\022\022\n\nframe_rate\030\007 \001(\001\022\014\n\004gain"
    "\030\010 \001(\001\022\031\n\021image_node_number\030\t \001(\005\022\022\n\nima"
    "ge_type\030\n \001(\005\022\037\n\003roi\030\013 \001(\0132\r.base.IntRec"
    "tH\000\210\001\001\022\032\n\rreverse_image\030\014 \001(\005H\001\210\001\001\022\024\n\014tr"
    "igger_type\030\r \001(\005\022A\n\016virtual_folder\030\016 \001(\013"
    "2$.camera_config.DirectoryCameraConfigH\002"
    "\210\001\001B\006\n\004_roiB\020\n\016_reverse_imageB\021\n\017_virtua"
    "l_folder\"Q\n\025DirectoryCameraConfig\022\021\n\tdir"
    "ectory\030\001 \001(\t\022\027\n\017image_extension\030\002 \001(\t\022\014\n"
    "\004loop\030\003 \001(\010\">\n\007Cameras\0223\n\016camera_configs"
    "\030\001 \003(\0132\033.camera_config.CameraConfigb\006pro"
    "to3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_camera_5fconfig_2eproto_deps[1] =
    {
        &::descriptor_table_base_2eproto,
};
static ::absl::once_flag descriptor_table_camera_5fconfig_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_camera_5fconfig_2eproto = {
    false,
    false,
    603,
    descriptor_table_protodef_camera_5fconfig_2eproto,
    "camera_config.proto",
    &descriptor_table_camera_5fconfig_2eproto_once,
    descriptor_table_camera_5fconfig_2eproto_deps,
    1,
    3,
    schemas,
    file_default_instances,
    TableStruct_camera_5fconfig_2eproto::offsets,
    file_level_enum_descriptors_camera_5fconfig_2eproto,
    file_level_service_descriptors_camera_5fconfig_2eproto,
};
namespace camera_config {
// ===================================================================

class CameraConfig::_Internal {
 public:
  using HasBits =
      decltype(std::declval<CameraConfig>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(CameraConfig, _impl_._has_bits_);
};

void CameraConfig::clear_roi() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.roi_ != nullptr) _impl_.roi_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
CameraConfig::CameraConfig(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:camera_config.CameraConfig)
}
inline PROTOBUF_NDEBUG_INLINE CameraConfig::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::camera_config::CameraConfig& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        name_(arena, from.name_),
        serial_number_(arena, from.serial_number_),
        type_(arena, from.type_) {}

CameraConfig::CameraConfig(
    ::google::protobuf::Arena* arena,
    const CameraConfig& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  CameraConfig* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.roi_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::base::IntRect>(
                              arena, *from._impl_.roi_)
                        : nullptr;
  _impl_.virtual_folder_ = (cached_has_bits & 0x00000002u) ? ::google::protobuf::Message::CopyConstruct<::camera_config::DirectoryCameraConfig>(
                              arena, *from._impl_.virtual_folder_)
                        : nullptr;
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, id_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, id_),
           offsetof(Impl_, trigger_type_) -
               offsetof(Impl_, id_) +
               sizeof(Impl_::trigger_type_));

  // @@protoc_insertion_point(copy_constructor:camera_config.CameraConfig)
}
inline PROTOBUF_NDEBUG_INLINE CameraConfig::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        name_(arena),
        serial_number_(arena),
        type_(arena) {}

inline void CameraConfig::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, roi_),
           0,
           offsetof(Impl_, trigger_type_) -
               offsetof(Impl_, roi_) +
               sizeof(Impl_::trigger_type_));
}
CameraConfig::~CameraConfig() {
  // @@protoc_insertion_point(destructor:camera_config.CameraConfig)
  SharedDtor(*this);
}
inline void CameraConfig::SharedDtor(MessageLite& self) {
  CameraConfig& this_ = static_cast<CameraConfig&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.name_.Destroy();
  this_._impl_.serial_number_.Destroy();
  this_._impl_.type_.Destroy();
  delete this_._impl_.roi_;
  delete this_._impl_.virtual_folder_;
  this_._impl_.~Impl_();
}

inline void* CameraConfig::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) CameraConfig(arena);
}
constexpr auto CameraConfig::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(CameraConfig),
                                            alignof(CameraConfig));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull CameraConfig::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_CameraConfig_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &CameraConfig::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<CameraConfig>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &CameraConfig::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<CameraConfig>(), &CameraConfig::ByteSizeLong,
            &CameraConfig::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(CameraConfig, _impl_._cached_size_),
        false,
    },
    &CameraConfig::kDescriptorMethods,
    &descriptor_table_camera_5fconfig_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* CameraConfig::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<4, 14, 2, 64, 2> CameraConfig::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CameraConfig, _impl_._has_bits_),
    0, // no _extensions_
    14, 120,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294950912,  // skipmap
    offsetof(decltype(_table_), field_entries),
    14,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::camera_config::CameraConfig>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int32 id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CameraConfig, _impl_.id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(CameraConfig, _impl_.id_)}},
    // string name = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(CameraConfig, _impl_.name_)}},
    // string serial_number = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(CameraConfig, _impl_.serial_number_)}},
    // string type = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(CameraConfig, _impl_.type_)}},
    // double exposure_time = 5;
    {::_pbi::TcParser::FastF64S1,
     {41, 63, 0, PROTOBUF_FIELD_OFFSET(CameraConfig, _impl_.exposure_time_)}},
    // int32 frame_count = 6;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CameraConfig, _impl_.frame_count_), 63>(),
     {48, 63, 0, PROTOBUF_FIELD_OFFSET(CameraConfig, _impl_.frame_count_)}},
    // double frame_rate = 7;
    {::_pbi::TcParser::FastF64S1,
     {57, 63, 0, PROTOBUF_FIELD_OFFSET(CameraConfig, _impl_.frame_rate_)}},
    // double gain = 8;
    {::_pbi::TcParser::FastF64S1,
     {65, 63, 0, PROTOBUF_FIELD_OFFSET(CameraConfig, _impl_.gain_)}},
    // int32 image_node_number = 9;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CameraConfig, _impl_.image_node_number_), 63>(),
     {72, 63, 0, PROTOBUF_FIELD_OFFSET(CameraConfig, _impl_.image_node_number_)}},
    // int32 image_type = 10;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CameraConfig, _impl_.image_type_), 63>(),
     {80, 63, 0, PROTOBUF_FIELD_OFFSET(CameraConfig, _impl_.image_type_)}},
    // optional .base.IntRect roi = 11;
    {::_pbi::TcParser::FastMtS1,
     {90, 0, 0, PROTOBUF_FIELD_OFFSET(CameraConfig, _impl_.roi_)}},
    // optional int32 reverse_image = 12;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CameraConfig, _impl_.reverse_image_), 2>(),
     {96, 2, 0, PROTOBUF_FIELD_OFFSET(CameraConfig, _impl_.reverse_image_)}},
    // int32 trigger_type = 13;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CameraConfig, _impl_.trigger_type_), 63>(),
     {104, 63, 0, PROTOBUF_FIELD_OFFSET(CameraConfig, _impl_.trigger_type_)}},
    // optional .camera_config.DirectoryCameraConfig virtual_folder = 14;
    {::_pbi::TcParser::FastMtS1,
     {114, 1, 1, PROTOBUF_FIELD_OFFSET(CameraConfig, _impl_.virtual_folder_)}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 id = 1;
    {PROTOBUF_FIELD_OFFSET(CameraConfig, _impl_.id_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string name = 2;
    {PROTOBUF_FIELD_OFFSET(CameraConfig, _impl_.name_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string serial_number = 3;
    {PROTOBUF_FIELD_OFFSET(CameraConfig, _impl_.serial_number_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string type = 4;
    {PROTOBUF_FIELD_OFFSET(CameraConfig, _impl_.type_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // double exposure_time = 5;
    {PROTOBUF_FIELD_OFFSET(CameraConfig, _impl_.exposure_time_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // int32 frame_count = 6;
    {PROTOBUF_FIELD_OFFSET(CameraConfig, _impl_.frame_count_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // double frame_rate = 7;
    {PROTOBUF_FIELD_OFFSET(CameraConfig, _impl_.frame_rate_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // double gain = 8;
    {PROTOBUF_FIELD_OFFSET(CameraConfig, _impl_.gain_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // int32 image_node_number = 9;
    {PROTOBUF_FIELD_OFFSET(CameraConfig, _impl_.image_node_number_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 image_type = 10;
    {PROTOBUF_FIELD_OFFSET(CameraConfig, _impl_.image_type_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // optional .base.IntRect roi = 11;
    {PROTOBUF_FIELD_OFFSET(CameraConfig, _impl_.roi_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // optional int32 reverse_image = 12;
    {PROTOBUF_FIELD_OFFSET(CameraConfig, _impl_.reverse_image_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // int32 trigger_type = 13;
    {PROTOBUF_FIELD_OFFSET(CameraConfig, _impl_.trigger_type_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // optional .camera_config.DirectoryCameraConfig virtual_folder = 14;
    {PROTOBUF_FIELD_OFFSET(CameraConfig, _impl_.virtual_folder_), _Internal::kHasBitsOffset + 1, 1,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::base::IntRect>()},
    {::_pbi::TcParser::GetTable<::camera_config::DirectoryCameraConfig>()},
  }}, {{
    "\32\0\4\15\4\0\0\0\0\0\0\0\0\0\0\0"
    "camera_config.CameraConfig"
    "name"
    "serial_number"
    "type"
  }},
};

PROTOBUF_NOINLINE void CameraConfig::Clear() {
// @@protoc_insertion_point(message_clear_start:camera_config.CameraConfig)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.name_.ClearToEmpty();
  _impl_.serial_number_.ClearToEmpty();
  _impl_.type_.ClearToEmpty();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(_impl_.roi_ != nullptr);
      _impl_.roi_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(_impl_.virtual_folder_ != nullptr);
      _impl_.virtual_folder_->Clear();
    }
  }
  ::memset(&_impl_.id_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.image_type_) -
      reinterpret_cast<char*>(&_impl_.id_)) + sizeof(_impl_.image_type_));
  _impl_.reverse_image_ = 0;
  _impl_.trigger_type_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* CameraConfig::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const CameraConfig& this_ = static_cast<const CameraConfig&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* CameraConfig::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const CameraConfig& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:camera_config.CameraConfig)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 id = 1;
          if (this_._internal_id() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_id(), target);
          }

          // string name = 2;
          if (!this_._internal_name().empty()) {
            const std::string& _s = this_._internal_name();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "camera_config.CameraConfig.name");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          // string serial_number = 3;
          if (!this_._internal_serial_number().empty()) {
            const std::string& _s = this_._internal_serial_number();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "camera_config.CameraConfig.serial_number");
            target = stream->WriteStringMaybeAliased(3, _s, target);
          }

          // string type = 4;
          if (!this_._internal_type().empty()) {
            const std::string& _s = this_._internal_type();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "camera_config.CameraConfig.type");
            target = stream->WriteStringMaybeAliased(4, _s, target);
          }

          // double exposure_time = 5;
          if (::absl::bit_cast<::uint64_t>(this_._internal_exposure_time()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                5, this_._internal_exposure_time(), target);
          }

          // int32 frame_count = 6;
          if (this_._internal_frame_count() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<6>(
                    stream, this_._internal_frame_count(), target);
          }

          // double frame_rate = 7;
          if (::absl::bit_cast<::uint64_t>(this_._internal_frame_rate()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                7, this_._internal_frame_rate(), target);
          }

          // double gain = 8;
          if (::absl::bit_cast<::uint64_t>(this_._internal_gain()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                8, this_._internal_gain(), target);
          }

          // int32 image_node_number = 9;
          if (this_._internal_image_node_number() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<9>(
                    stream, this_._internal_image_node_number(), target);
          }

          // int32 image_type = 10;
          if (this_._internal_image_type() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<10>(
                    stream, this_._internal_image_type(), target);
          }

          cached_has_bits = this_._impl_._has_bits_[0];
          // optional .base.IntRect roi = 11;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                11, *this_._impl_.roi_, this_._impl_.roi_->GetCachedSize(), target,
                stream);
          }

          // optional int32 reverse_image = 12;
          if (cached_has_bits & 0x00000004u) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<12>(
                    stream, this_._internal_reverse_image(), target);
          }

          // int32 trigger_type = 13;
          if (this_._internal_trigger_type() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<13>(
                    stream, this_._internal_trigger_type(), target);
          }

          // optional .camera_config.DirectoryCameraConfig virtual_folder = 14;
          if (cached_has_bits & 0x00000002u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                14, *this_._impl_.virtual_folder_, this_._impl_.virtual_folder_->GetCachedSize(), target,
                stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:camera_config.CameraConfig)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t CameraConfig::ByteSizeLong(const MessageLite& base) {
          const CameraConfig& this_ = static_cast<const CameraConfig&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t CameraConfig::ByteSizeLong() const {
          const CameraConfig& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:camera_config.CameraConfig)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string name = 2;
            if (!this_._internal_name().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_name());
            }
            // string serial_number = 3;
            if (!this_._internal_serial_number().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_serial_number());
            }
            // string type = 4;
            if (!this_._internal_type().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_type());
            }
          }
          cached_has_bits = this_._impl_._has_bits_[0];
          if (cached_has_bits & 0x00000003u) {
            // optional .base.IntRect roi = 11;
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.roi_);
            }
            // optional .camera_config.DirectoryCameraConfig virtual_folder = 14;
            if (cached_has_bits & 0x00000002u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.virtual_folder_);
            }
          }
           {
            // int32 id = 1;
            if (this_._internal_id() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_id());
            }
            // int32 frame_count = 6;
            if (this_._internal_frame_count() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_frame_count());
            }
            // double exposure_time = 5;
            if (::absl::bit_cast<::uint64_t>(this_._internal_exposure_time()) != 0) {
              total_size += 9;
            }
            // double frame_rate = 7;
            if (::absl::bit_cast<::uint64_t>(this_._internal_frame_rate()) != 0) {
              total_size += 9;
            }
            // double gain = 8;
            if (::absl::bit_cast<::uint64_t>(this_._internal_gain()) != 0) {
              total_size += 9;
            }
            // int32 image_node_number = 9;
            if (this_._internal_image_node_number() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_image_node_number());
            }
            // int32 image_type = 10;
            if (this_._internal_image_type() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_image_type());
            }
          }
           {
            // optional int32 reverse_image = 12;
            if (cached_has_bits & 0x00000004u) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_reverse_image());
            }
          }
           {
            // int32 trigger_type = 13;
            if (this_._internal_trigger_type() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_trigger_type());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void CameraConfig::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<CameraConfig*>(&to_msg);
  auto& from = static_cast<const CameraConfig&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:camera_config.CameraConfig)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  if (!from._internal_serial_number().empty()) {
    _this->_internal_set_serial_number(from._internal_serial_number());
  }
  if (!from._internal_type().empty()) {
    _this->_internal_set_type(from._internal_type());
  }
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(from._impl_.roi_ != nullptr);
      if (_this->_impl_.roi_ == nullptr) {
        _this->_impl_.roi_ =
            ::google::protobuf::Message::CopyConstruct<::base::IntRect>(arena, *from._impl_.roi_);
      } else {
        _this->_impl_.roi_->MergeFrom(*from._impl_.roi_);
      }
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(from._impl_.virtual_folder_ != nullptr);
      if (_this->_impl_.virtual_folder_ == nullptr) {
        _this->_impl_.virtual_folder_ =
            ::google::protobuf::Message::CopyConstruct<::camera_config::DirectoryCameraConfig>(arena, *from._impl_.virtual_folder_);
      } else {
        _this->_impl_.virtual_folder_->MergeFrom(*from._impl_.virtual_folder_);
      }
    }
  }
  if (from._internal_id() != 0) {
    _this->_impl_.id_ = from._impl_.id_;
  }
  if (from._internal_frame_count() != 0) {
    _this->_impl_.frame_count_ = from._impl_.frame_count_;
  }
  if (::absl::bit_cast<::uint64_t>(from._internal_exposure_time()) != 0) {
    _this->_impl_.exposure_time_ = from._impl_.exposure_time_;
  }
  if (::absl::bit_cast<::uint64_t>(from._internal_frame_rate()) != 0) {
    _this->_impl_.frame_rate_ = from._impl_.frame_rate_;
  }
  if (::absl::bit_cast<::uint64_t>(from._internal_gain()) != 0) {
    _this->_impl_.gain_ = from._impl_.gain_;
  }
  if (from._internal_image_node_number() != 0) {
    _this->_impl_.image_node_number_ = from._impl_.image_node_number_;
  }
  if (from._internal_image_type() != 0) {
    _this->_impl_.image_type_ = from._impl_.image_type_;
  }
  if (cached_has_bits & 0x00000004u) {
    _this->_impl_.reverse_image_ = from._impl_.reverse_image_;
  }
  if (from._internal_trigger_type() != 0) {
    _this->_impl_.trigger_type_ = from._impl_.trigger_type_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CameraConfig::CopyFrom(const CameraConfig& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:camera_config.CameraConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CameraConfig::InternalSwap(CameraConfig* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.serial_number_, &other->_impl_.serial_number_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.type_, &other->_impl_.type_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CameraConfig, _impl_.trigger_type_)
      + sizeof(CameraConfig::_impl_.trigger_type_)
      - PROTOBUF_FIELD_OFFSET(CameraConfig, _impl_.roi_)>(
          reinterpret_cast<char*>(&_impl_.roi_),
          reinterpret_cast<char*>(&other->_impl_.roi_));
}

::google::protobuf::Metadata CameraConfig::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class DirectoryCameraConfig::_Internal {
 public:
};

DirectoryCameraConfig::DirectoryCameraConfig(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:camera_config.DirectoryCameraConfig)
}
inline PROTOBUF_NDEBUG_INLINE DirectoryCameraConfig::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::camera_config::DirectoryCameraConfig& from_msg)
      : directory_(arena, from.directory_),
        image_extension_(arena, from.image_extension_),
        _cached_size_{0} {}

DirectoryCameraConfig::DirectoryCameraConfig(
    ::google::protobuf::Arena* arena,
    const DirectoryCameraConfig& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  DirectoryCameraConfig* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.loop_ = from._impl_.loop_;

  // @@protoc_insertion_point(copy_constructor:camera_config.DirectoryCameraConfig)
}
inline PROTOBUF_NDEBUG_INLINE DirectoryCameraConfig::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : directory_(arena),
        image_extension_(arena),
        _cached_size_{0} {}

inline void DirectoryCameraConfig::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.loop_ = {};
}
DirectoryCameraConfig::~DirectoryCameraConfig() {
  // @@protoc_insertion_point(destructor:camera_config.DirectoryCameraConfig)
  SharedDtor(*this);
}
inline void DirectoryCameraConfig::SharedDtor(MessageLite& self) {
  DirectoryCameraConfig& this_ = static_cast<DirectoryCameraConfig&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.directory_.Destroy();
  this_._impl_.image_extension_.Destroy();
  this_._impl_.~Impl_();
}

inline void* DirectoryCameraConfig::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) DirectoryCameraConfig(arena);
}
constexpr auto DirectoryCameraConfig::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(DirectoryCameraConfig),
                                            alignof(DirectoryCameraConfig));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull DirectoryCameraConfig::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_DirectoryCameraConfig_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &DirectoryCameraConfig::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<DirectoryCameraConfig>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &DirectoryCameraConfig::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<DirectoryCameraConfig>(), &DirectoryCameraConfig::ByteSizeLong,
            &DirectoryCameraConfig::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(DirectoryCameraConfig, _impl_._cached_size_),
        false,
    },
    &DirectoryCameraConfig::kDescriptorMethods,
    &descriptor_table_camera_5fconfig_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* DirectoryCameraConfig::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 68, 2> DirectoryCameraConfig::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::camera_config::DirectoryCameraConfig>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string directory = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(DirectoryCameraConfig, _impl_.directory_)}},
    // string image_extension = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(DirectoryCameraConfig, _impl_.image_extension_)}},
    // bool loop = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(DirectoryCameraConfig, _impl_.loop_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(DirectoryCameraConfig, _impl_.loop_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string directory = 1;
    {PROTOBUF_FIELD_OFFSET(DirectoryCameraConfig, _impl_.directory_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string image_extension = 2;
    {PROTOBUF_FIELD_OFFSET(DirectoryCameraConfig, _impl_.image_extension_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // bool loop = 3;
    {PROTOBUF_FIELD_OFFSET(DirectoryCameraConfig, _impl_.loop_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
    "\43\11\17\0\0\0\0\0"
    "camera_config.DirectoryCameraConfig"
    "directory"
    "image_extension"
  }},
};

PROTOBUF_NOINLINE void DirectoryCameraConfig::Clear() {
// @@protoc_insertion_point(message_clear_start:camera_config.DirectoryCameraConfig)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.directory_.ClearToEmpty();
  _impl_.image_extension_.ClearToEmpty();
  _impl_.loop_ = false;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* DirectoryCameraConfig::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const DirectoryCameraConfig& this_ = static_cast<const DirectoryCameraConfig&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* DirectoryCameraConfig::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const DirectoryCameraConfig& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:camera_config.DirectoryCameraConfig)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string directory = 1;
          if (!this_._internal_directory().empty()) {
            const std::string& _s = this_._internal_directory();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "camera_config.DirectoryCameraConfig.directory");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // string image_extension = 2;
          if (!this_._internal_image_extension().empty()) {
            const std::string& _s = this_._internal_image_extension();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "camera_config.DirectoryCameraConfig.image_extension");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          // bool loop = 3;
          if (this_._internal_loop() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                3, this_._internal_loop(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:camera_config.DirectoryCameraConfig)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t DirectoryCameraConfig::ByteSizeLong(const MessageLite& base) {
          const DirectoryCameraConfig& this_ = static_cast<const DirectoryCameraConfig&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t DirectoryCameraConfig::ByteSizeLong() const {
          const DirectoryCameraConfig& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:camera_config.DirectoryCameraConfig)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string directory = 1;
            if (!this_._internal_directory().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_directory());
            }
            // string image_extension = 2;
            if (!this_._internal_image_extension().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_image_extension());
            }
            // bool loop = 3;
            if (this_._internal_loop() != 0) {
              total_size += 2;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void DirectoryCameraConfig::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<DirectoryCameraConfig*>(&to_msg);
  auto& from = static_cast<const DirectoryCameraConfig&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:camera_config.DirectoryCameraConfig)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_directory().empty()) {
    _this->_internal_set_directory(from._internal_directory());
  }
  if (!from._internal_image_extension().empty()) {
    _this->_internal_set_image_extension(from._internal_image_extension());
  }
  if (from._internal_loop() != 0) {
    _this->_impl_.loop_ = from._impl_.loop_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void DirectoryCameraConfig::CopyFrom(const DirectoryCameraConfig& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:camera_config.DirectoryCameraConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void DirectoryCameraConfig::InternalSwap(DirectoryCameraConfig* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.directory_, &other->_impl_.directory_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.image_extension_, &other->_impl_.image_extension_, arena);
        swap(_impl_.loop_, other->_impl_.loop_);
}

::google::protobuf::Metadata DirectoryCameraConfig::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Cameras::_Internal {
 public:
};

Cameras::Cameras(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:camera_config.Cameras)
}
inline PROTOBUF_NDEBUG_INLINE Cameras::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::camera_config::Cameras& from_msg)
      : camera_configs_{visibility, arena, from.camera_configs_},
        _cached_size_{0} {}

Cameras::Cameras(
    ::google::protobuf::Arena* arena,
    const Cameras& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Cameras* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:camera_config.Cameras)
}
inline PROTOBUF_NDEBUG_INLINE Cameras::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : camera_configs_{visibility, arena},
        _cached_size_{0} {}

inline void Cameras::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
Cameras::~Cameras() {
  // @@protoc_insertion_point(destructor:camera_config.Cameras)
  SharedDtor(*this);
}
inline void Cameras::SharedDtor(MessageLite& self) {
  Cameras& this_ = static_cast<Cameras&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* Cameras::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) Cameras(arena);
}
constexpr auto Cameras::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(Cameras, _impl_.camera_configs_) +
          decltype(Cameras::_impl_.camera_configs_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(Cameras), alignof(Cameras), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&Cameras::PlacementNew_,
                                 sizeof(Cameras),
                                 alignof(Cameras));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull Cameras::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_Cameras_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &Cameras::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<Cameras>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &Cameras::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<Cameras>(), &Cameras::ByteSizeLong,
            &Cameras::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(Cameras, _impl_._cached_size_),
        false,
    },
    &Cameras::kDescriptorMethods,
    &descriptor_table_camera_5fconfig_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* Cameras::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2> Cameras::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::camera_config::Cameras>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .camera_config.CameraConfig camera_configs = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(Cameras, _impl_.camera_configs_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .camera_config.CameraConfig camera_configs = 1;
    {PROTOBUF_FIELD_OFFSET(Cameras, _impl_.camera_configs_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::camera_config::CameraConfig>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void Cameras::Clear() {
// @@protoc_insertion_point(message_clear_start:camera_config.Cameras)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.camera_configs_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Cameras::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Cameras& this_ = static_cast<const Cameras&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Cameras::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Cameras& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:camera_config.Cameras)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // repeated .camera_config.CameraConfig camera_configs = 1;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_camera_configs_size());
               i < n; i++) {
            const auto& repfield = this_._internal_camera_configs().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    1, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:camera_config.Cameras)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Cameras::ByteSizeLong(const MessageLite& base) {
          const Cameras& this_ = static_cast<const Cameras&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Cameras::ByteSizeLong() const {
          const Cameras& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:camera_config.Cameras)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated .camera_config.CameraConfig camera_configs = 1;
            {
              total_size += 1UL * this_._internal_camera_configs_size();
              for (const auto& msg : this_._internal_camera_configs()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void Cameras::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Cameras*>(&to_msg);
  auto& from = static_cast<const Cameras&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:camera_config.Cameras)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_camera_configs()->MergeFrom(
      from._internal_camera_configs());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Cameras::CopyFrom(const Cameras& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:camera_config.Cameras)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Cameras::InternalSwap(Cameras* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.camera_configs_.InternalSwap(&other->_impl_.camera_configs_);
}

::google::protobuf::Metadata Cameras::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace camera_config
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_camera_5fconfig_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
