// copyright 2025 YottaImage. All rights reserved.
// author zhangshuangcheng
// date 2026/03/28 17:13

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: camera_config.proto
// Protobuf C++ Version: 5.29.3

#ifndef camera_5fconfig_2eproto_2epb_2eh
#define camera_5fconfig_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029003
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "base.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_camera_5fconfig_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_camera_5fconfig_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_camera_5fconfig_2eproto;
namespace camera_config {
class CameraConfig;
struct CameraConfigDefaultTypeInternal;
extern CameraConfigDefaultTypeInternal _CameraConfig_default_instance_;
class Cameras;
struct CamerasDefaultTypeInternal;
extern CamerasDefaultTypeInternal _Cameras_default_instance_;
class DirectoryCameraConfig;
struct DirectoryCameraConfigDefaultTypeInternal;
extern DirectoryCameraConfigDefaultTypeInternal _DirectoryCameraConfig_default_instance_;
}  // namespace camera_config
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace camera_config {

// ===================================================================


// -------------------------------------------------------------------

class DirectoryCameraConfig final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:camera_config.DirectoryCameraConfig) */ {
 public:
  inline DirectoryCameraConfig() : DirectoryCameraConfig(nullptr) {}
  ~DirectoryCameraConfig() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(DirectoryCameraConfig* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(DirectoryCameraConfig));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR DirectoryCameraConfig(
      ::google::protobuf::internal::ConstantInitialized);

  inline DirectoryCameraConfig(const DirectoryCameraConfig& from) : DirectoryCameraConfig(nullptr, from) {}
  inline DirectoryCameraConfig(DirectoryCameraConfig&& from) noexcept
      : DirectoryCameraConfig(nullptr, std::move(from)) {}
  inline DirectoryCameraConfig& operator=(const DirectoryCameraConfig& from) {
    CopyFrom(from);
    return *this;
  }
  inline DirectoryCameraConfig& operator=(DirectoryCameraConfig&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DirectoryCameraConfig& default_instance() {
    return *internal_default_instance();
  }
  static inline const DirectoryCameraConfig* internal_default_instance() {
    return reinterpret_cast<const DirectoryCameraConfig*>(
        &_DirectoryCameraConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(DirectoryCameraConfig& a, DirectoryCameraConfig& b) { a.Swap(&b); }
  inline void Swap(DirectoryCameraConfig* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DirectoryCameraConfig* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DirectoryCameraConfig* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<DirectoryCameraConfig>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const DirectoryCameraConfig& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const DirectoryCameraConfig& from) { DirectoryCameraConfig::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(DirectoryCameraConfig* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "camera_config.DirectoryCameraConfig"; }

 protected:
  explicit DirectoryCameraConfig(::google::protobuf::Arena* arena);
  DirectoryCameraConfig(::google::protobuf::Arena* arena, const DirectoryCameraConfig& from);
  DirectoryCameraConfig(::google::protobuf::Arena* arena, DirectoryCameraConfig&& from) noexcept
      : DirectoryCameraConfig(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kDirectoryFieldNumber = 1,
    kImageExtensionFieldNumber = 2,
    kLoopFieldNumber = 3,
  };
  // string directory = 1;
  void clear_directory() ;
  const std::string& directory() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_directory(Arg_&& arg, Args_... args);
  std::string* mutable_directory();
  PROTOBUF_NODISCARD std::string* release_directory();
  void set_allocated_directory(std::string* value);

  private:
  const std::string& _internal_directory() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_directory(
      const std::string& value);
  std::string* _internal_mutable_directory();

  public:
  // string image_extension = 2;
  void clear_image_extension() ;
  const std::string& image_extension() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_image_extension(Arg_&& arg, Args_... args);
  std::string* mutable_image_extension();
  PROTOBUF_NODISCARD std::string* release_image_extension();
  void set_allocated_image_extension(std::string* value);

  private:
  const std::string& _internal_image_extension() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_image_extension(
      const std::string& value);
  std::string* _internal_mutable_image_extension();

  public:
  // bool loop = 3;
  void clear_loop() ;
  bool loop() const;
  void set_loop(bool value);

  private:
  bool _internal_loop() const;
  void _internal_set_loop(bool value);

  public:
  // @@protoc_insertion_point(class_scope:camera_config.DirectoryCameraConfig)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      68, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const DirectoryCameraConfig& from_msg);
    ::google::protobuf::internal::ArenaStringPtr directory_;
    ::google::protobuf::internal::ArenaStringPtr image_extension_;
    bool loop_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_camera_5fconfig_2eproto;
};
// -------------------------------------------------------------------

class CameraConfig final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:camera_config.CameraConfig) */ {
 public:
  inline CameraConfig() : CameraConfig(nullptr) {}
  ~CameraConfig() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CameraConfig* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CameraConfig));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR CameraConfig(
      ::google::protobuf::internal::ConstantInitialized);

  inline CameraConfig(const CameraConfig& from) : CameraConfig(nullptr, from) {}
  inline CameraConfig(CameraConfig&& from) noexcept
      : CameraConfig(nullptr, std::move(from)) {}
  inline CameraConfig& operator=(const CameraConfig& from) {
    CopyFrom(from);
    return *this;
  }
  inline CameraConfig& operator=(CameraConfig&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CameraConfig& default_instance() {
    return *internal_default_instance();
  }
  static inline const CameraConfig* internal_default_instance() {
    return reinterpret_cast<const CameraConfig*>(
        &_CameraConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(CameraConfig& a, CameraConfig& b) { a.Swap(&b); }
  inline void Swap(CameraConfig* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CameraConfig* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CameraConfig* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<CameraConfig>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CameraConfig& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const CameraConfig& from) { CameraConfig::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CameraConfig* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "camera_config.CameraConfig"; }

 protected:
  explicit CameraConfig(::google::protobuf::Arena* arena);
  CameraConfig(::google::protobuf::Arena* arena, const CameraConfig& from);
  CameraConfig(::google::protobuf::Arena* arena, CameraConfig&& from) noexcept
      : CameraConfig(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kNameFieldNumber = 2,
    kSerialNumberFieldNumber = 3,
    kTypeFieldNumber = 4,
    kRoiFieldNumber = 11,
    kVirtualFolderFieldNumber = 14,
    kIdFieldNumber = 1,
    kFrameCountFieldNumber = 6,
    kExposureTimeFieldNumber = 5,
    kFrameRateFieldNumber = 7,
    kGainFieldNumber = 8,
    kImageNodeNumberFieldNumber = 9,
    kImageTypeFieldNumber = 10,
    kReverseImageFieldNumber = 12,
    kTriggerTypeFieldNumber = 13,
  };
  // string name = 2;
  void clear_name() ;
  const std::string& name() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_name(Arg_&& arg, Args_... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* value);

  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(
      const std::string& value);
  std::string* _internal_mutable_name();

  public:
  // string serial_number = 3;
  void clear_serial_number() ;
  const std::string& serial_number() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_serial_number(Arg_&& arg, Args_... args);
  std::string* mutable_serial_number();
  PROTOBUF_NODISCARD std::string* release_serial_number();
  void set_allocated_serial_number(std::string* value);

  private:
  const std::string& _internal_serial_number() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_serial_number(
      const std::string& value);
  std::string* _internal_mutable_serial_number();

  public:
  // string type = 4;
  void clear_type() ;
  const std::string& type() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_type(Arg_&& arg, Args_... args);
  std::string* mutable_type();
  PROTOBUF_NODISCARD std::string* release_type();
  void set_allocated_type(std::string* value);

  private:
  const std::string& _internal_type() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_type(
      const std::string& value);
  std::string* _internal_mutable_type();

  public:
  // optional .base.IntRect roi = 11;
  bool has_roi() const;
  void clear_roi() ;
  const ::base::IntRect& roi() const;
  PROTOBUF_NODISCARD ::base::IntRect* release_roi();
  ::base::IntRect* mutable_roi();
  void set_allocated_roi(::base::IntRect* value);
  void unsafe_arena_set_allocated_roi(::base::IntRect* value);
  ::base::IntRect* unsafe_arena_release_roi();

  private:
  const ::base::IntRect& _internal_roi() const;
  ::base::IntRect* _internal_mutable_roi();

  public:
  // optional .camera_config.DirectoryCameraConfig virtual_folder = 14;
  bool has_virtual_folder() const;
  void clear_virtual_folder() ;
  const ::camera_config::DirectoryCameraConfig& virtual_folder() const;
  PROTOBUF_NODISCARD ::camera_config::DirectoryCameraConfig* release_virtual_folder();
  ::camera_config::DirectoryCameraConfig* mutable_virtual_folder();
  void set_allocated_virtual_folder(::camera_config::DirectoryCameraConfig* value);
  void unsafe_arena_set_allocated_virtual_folder(::camera_config::DirectoryCameraConfig* value);
  ::camera_config::DirectoryCameraConfig* unsafe_arena_release_virtual_folder();

  private:
  const ::camera_config::DirectoryCameraConfig& _internal_virtual_folder() const;
  ::camera_config::DirectoryCameraConfig* _internal_mutable_virtual_folder();

  public:
  // int32 id = 1;
  void clear_id() ;
  ::int32_t id() const;
  void set_id(::int32_t value);

  private:
  ::int32_t _internal_id() const;
  void _internal_set_id(::int32_t value);

  public:
  // int32 frame_count = 6;
  void clear_frame_count() ;
  ::int32_t frame_count() const;
  void set_frame_count(::int32_t value);

  private:
  ::int32_t _internal_frame_count() const;
  void _internal_set_frame_count(::int32_t value);

  public:
  // double exposure_time = 5;
  void clear_exposure_time() ;
  double exposure_time() const;
  void set_exposure_time(double value);

  private:
  double _internal_exposure_time() const;
  void _internal_set_exposure_time(double value);

  public:
  // double frame_rate = 7;
  void clear_frame_rate() ;
  double frame_rate() const;
  void set_frame_rate(double value);

  private:
  double _internal_frame_rate() const;
  void _internal_set_frame_rate(double value);

  public:
  // double gain = 8;
  void clear_gain() ;
  double gain() const;
  void set_gain(double value);

  private:
  double _internal_gain() const;
  void _internal_set_gain(double value);

  public:
  // int32 image_node_number = 9;
  void clear_image_node_number() ;
  ::int32_t image_node_number() const;
  void set_image_node_number(::int32_t value);

  private:
  ::int32_t _internal_image_node_number() const;
  void _internal_set_image_node_number(::int32_t value);

  public:
  // int32 image_type = 10;
  void clear_image_type() ;
  ::int32_t image_type() const;
  void set_image_type(::int32_t value);

  private:
  ::int32_t _internal_image_type() const;
  void _internal_set_image_type(::int32_t value);

  public:
  // optional int32 reverse_image = 12;
  bool has_reverse_image() const;
  void clear_reverse_image() ;
  ::int32_t reverse_image() const;
  void set_reverse_image(::int32_t value);

  private:
  ::int32_t _internal_reverse_image() const;
  void _internal_set_reverse_image(::int32_t value);

  public:
  // int32 trigger_type = 13;
  void clear_trigger_type() ;
  ::int32_t trigger_type() const;
  void set_trigger_type(::int32_t value);

  private:
  ::int32_t _internal_trigger_type() const;
  void _internal_set_trigger_type(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:camera_config.CameraConfig)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      4, 14, 2,
      64, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const CameraConfig& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr name_;
    ::google::protobuf::internal::ArenaStringPtr serial_number_;
    ::google::protobuf::internal::ArenaStringPtr type_;
    ::base::IntRect* roi_;
    ::camera_config::DirectoryCameraConfig* virtual_folder_;
    ::int32_t id_;
    ::int32_t frame_count_;
    double exposure_time_;
    double frame_rate_;
    double gain_;
    ::int32_t image_node_number_;
    ::int32_t image_type_;
    ::int32_t reverse_image_;
    ::int32_t trigger_type_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_camera_5fconfig_2eproto;
};
// -------------------------------------------------------------------

class Cameras final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:camera_config.Cameras) */ {
 public:
  inline Cameras() : Cameras(nullptr) {}
  ~Cameras() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Cameras* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Cameras));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Cameras(
      ::google::protobuf::internal::ConstantInitialized);

  inline Cameras(const Cameras& from) : Cameras(nullptr, from) {}
  inline Cameras(Cameras&& from) noexcept
      : Cameras(nullptr, std::move(from)) {}
  inline Cameras& operator=(const Cameras& from) {
    CopyFrom(from);
    return *this;
  }
  inline Cameras& operator=(Cameras&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Cameras& default_instance() {
    return *internal_default_instance();
  }
  static inline const Cameras* internal_default_instance() {
    return reinterpret_cast<const Cameras*>(
        &_Cameras_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(Cameras& a, Cameras& b) { a.Swap(&b); }
  inline void Swap(Cameras* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Cameras* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Cameras* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Cameras>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Cameras& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Cameras& from) { Cameras::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Cameras* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "camera_config.Cameras"; }

 protected:
  explicit Cameras(::google::protobuf::Arena* arena);
  Cameras(::google::protobuf::Arena* arena, const Cameras& from);
  Cameras(::google::protobuf::Arena* arena, Cameras&& from) noexcept
      : Cameras(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kCameraConfigsFieldNumber = 1,
  };
  // repeated .camera_config.CameraConfig camera_configs = 1;
  int camera_configs_size() const;
  private:
  int _internal_camera_configs_size() const;

  public:
  void clear_camera_configs() ;
  ::camera_config::CameraConfig* mutable_camera_configs(int index);
  ::google::protobuf::RepeatedPtrField<::camera_config::CameraConfig>* mutable_camera_configs();

  private:
  const ::google::protobuf::RepeatedPtrField<::camera_config::CameraConfig>& _internal_camera_configs() const;
  ::google::protobuf::RepeatedPtrField<::camera_config::CameraConfig>* _internal_mutable_camera_configs();
  public:
  const ::camera_config::CameraConfig& camera_configs(int index) const;
  ::camera_config::CameraConfig* add_camera_configs();
  const ::google::protobuf::RepeatedPtrField<::camera_config::CameraConfig>& camera_configs() const;
  // @@protoc_insertion_point(class_scope:camera_config.Cameras)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 1,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const Cameras& from_msg);
    ::google::protobuf::RepeatedPtrField< ::camera_config::CameraConfig > camera_configs_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_camera_5fconfig_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// CameraConfig

// int32 id = 1;
inline void CameraConfig::clear_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = 0;
}
inline ::int32_t CameraConfig::id() const {
  // @@protoc_insertion_point(field_get:camera_config.CameraConfig.id)
  return _internal_id();
}
inline void CameraConfig::set_id(::int32_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:camera_config.CameraConfig.id)
}
inline ::int32_t CameraConfig::_internal_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.id_;
}
inline void CameraConfig::_internal_set_id(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = value;
}

// string name = 2;
inline void CameraConfig::clear_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.ClearToEmpty();
}
inline const std::string& CameraConfig::name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:camera_config.CameraConfig.name)
  return _internal_name();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void CameraConfig::set_name(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:camera_config.CameraConfig.name)
}
inline std::string* CameraConfig::mutable_name() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:camera_config.CameraConfig.name)
  return _s;
}
inline const std::string& CameraConfig::_internal_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.name_.Get();
}
inline void CameraConfig::_internal_set_name(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.Set(value, GetArena());
}
inline std::string* CameraConfig::_internal_mutable_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.name_.Mutable( GetArena());
}
inline std::string* CameraConfig::release_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:camera_config.CameraConfig.name)
  return _impl_.name_.Release();
}
inline void CameraConfig::set_allocated_name(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:camera_config.CameraConfig.name)
}

// string serial_number = 3;
inline void CameraConfig::clear_serial_number() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.serial_number_.ClearToEmpty();
}
inline const std::string& CameraConfig::serial_number() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:camera_config.CameraConfig.serial_number)
  return _internal_serial_number();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void CameraConfig::set_serial_number(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.serial_number_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:camera_config.CameraConfig.serial_number)
}
inline std::string* CameraConfig::mutable_serial_number() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_serial_number();
  // @@protoc_insertion_point(field_mutable:camera_config.CameraConfig.serial_number)
  return _s;
}
inline const std::string& CameraConfig::_internal_serial_number() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.serial_number_.Get();
}
inline void CameraConfig::_internal_set_serial_number(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.serial_number_.Set(value, GetArena());
}
inline std::string* CameraConfig::_internal_mutable_serial_number() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.serial_number_.Mutable( GetArena());
}
inline std::string* CameraConfig::release_serial_number() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:camera_config.CameraConfig.serial_number)
  return _impl_.serial_number_.Release();
}
inline void CameraConfig::set_allocated_serial_number(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.serial_number_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.serial_number_.IsDefault()) {
    _impl_.serial_number_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:camera_config.CameraConfig.serial_number)
}

// string type = 4;
inline void CameraConfig::clear_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_.ClearToEmpty();
}
inline const std::string& CameraConfig::type() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:camera_config.CameraConfig.type)
  return _internal_type();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void CameraConfig::set_type(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:camera_config.CameraConfig.type)
}
inline std::string* CameraConfig::mutable_type() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_type();
  // @@protoc_insertion_point(field_mutable:camera_config.CameraConfig.type)
  return _s;
}
inline const std::string& CameraConfig::_internal_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.type_.Get();
}
inline void CameraConfig::_internal_set_type(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_.Set(value, GetArena());
}
inline std::string* CameraConfig::_internal_mutable_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.type_.Mutable( GetArena());
}
inline std::string* CameraConfig::release_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:camera_config.CameraConfig.type)
  return _impl_.type_.Release();
}
inline void CameraConfig::set_allocated_type(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.type_.IsDefault()) {
    _impl_.type_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:camera_config.CameraConfig.type)
}

// double exposure_time = 5;
inline void CameraConfig::clear_exposure_time() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.exposure_time_ = 0;
}
inline double CameraConfig::exposure_time() const {
  // @@protoc_insertion_point(field_get:camera_config.CameraConfig.exposure_time)
  return _internal_exposure_time();
}
inline void CameraConfig::set_exposure_time(double value) {
  _internal_set_exposure_time(value);
  // @@protoc_insertion_point(field_set:camera_config.CameraConfig.exposure_time)
}
inline double CameraConfig::_internal_exposure_time() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.exposure_time_;
}
inline void CameraConfig::_internal_set_exposure_time(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.exposure_time_ = value;
}

// int32 frame_count = 6;
inline void CameraConfig::clear_frame_count() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.frame_count_ = 0;
}
inline ::int32_t CameraConfig::frame_count() const {
  // @@protoc_insertion_point(field_get:camera_config.CameraConfig.frame_count)
  return _internal_frame_count();
}
inline void CameraConfig::set_frame_count(::int32_t value) {
  _internal_set_frame_count(value);
  // @@protoc_insertion_point(field_set:camera_config.CameraConfig.frame_count)
}
inline ::int32_t CameraConfig::_internal_frame_count() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.frame_count_;
}
inline void CameraConfig::_internal_set_frame_count(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.frame_count_ = value;
}

// double frame_rate = 7;
inline void CameraConfig::clear_frame_rate() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.frame_rate_ = 0;
}
inline double CameraConfig::frame_rate() const {
  // @@protoc_insertion_point(field_get:camera_config.CameraConfig.frame_rate)
  return _internal_frame_rate();
}
inline void CameraConfig::set_frame_rate(double value) {
  _internal_set_frame_rate(value);
  // @@protoc_insertion_point(field_set:camera_config.CameraConfig.frame_rate)
}
inline double CameraConfig::_internal_frame_rate() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.frame_rate_;
}
inline void CameraConfig::_internal_set_frame_rate(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.frame_rate_ = value;
}

// double gain = 8;
inline void CameraConfig::clear_gain() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.gain_ = 0;
}
inline double CameraConfig::gain() const {
  // @@protoc_insertion_point(field_get:camera_config.CameraConfig.gain)
  return _internal_gain();
}
inline void CameraConfig::set_gain(double value) {
  _internal_set_gain(value);
  // @@protoc_insertion_point(field_set:camera_config.CameraConfig.gain)
}
inline double CameraConfig::_internal_gain() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.gain_;
}
inline void CameraConfig::_internal_set_gain(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.gain_ = value;
}

// int32 image_node_number = 9;
inline void CameraConfig::clear_image_node_number() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.image_node_number_ = 0;
}
inline ::int32_t CameraConfig::image_node_number() const {
  // @@protoc_insertion_point(field_get:camera_config.CameraConfig.image_node_number)
  return _internal_image_node_number();
}
inline void CameraConfig::set_image_node_number(::int32_t value) {
  _internal_set_image_node_number(value);
  // @@protoc_insertion_point(field_set:camera_config.CameraConfig.image_node_number)
}
inline ::int32_t CameraConfig::_internal_image_node_number() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.image_node_number_;
}
inline void CameraConfig::_internal_set_image_node_number(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.image_node_number_ = value;
}

// int32 image_type = 10;
inline void CameraConfig::clear_image_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.image_type_ = 0;
}
inline ::int32_t CameraConfig::image_type() const {
  // @@protoc_insertion_point(field_get:camera_config.CameraConfig.image_type)
  return _internal_image_type();
}
inline void CameraConfig::set_image_type(::int32_t value) {
  _internal_set_image_type(value);
  // @@protoc_insertion_point(field_set:camera_config.CameraConfig.image_type)
}
inline ::int32_t CameraConfig::_internal_image_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.image_type_;
}
inline void CameraConfig::_internal_set_image_type(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.image_type_ = value;
}

// optional .base.IntRect roi = 11;
inline bool CameraConfig::has_roi() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.roi_ != nullptr);
  return value;
}
inline const ::base::IntRect& CameraConfig::_internal_roi() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::base::IntRect* p = _impl_.roi_;
  return p != nullptr ? *p : reinterpret_cast<const ::base::IntRect&>(::base::_IntRect_default_instance_);
}
inline const ::base::IntRect& CameraConfig::roi() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:camera_config.CameraConfig.roi)
  return _internal_roi();
}
inline void CameraConfig::unsafe_arena_set_allocated_roi(::base::IntRect* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.roi_);
  }
  _impl_.roi_ = reinterpret_cast<::base::IntRect*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:camera_config.CameraConfig.roi)
}
inline ::base::IntRect* CameraConfig::release_roi() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::base::IntRect* released = _impl_.roi_;
  _impl_.roi_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::base::IntRect* CameraConfig::unsafe_arena_release_roi() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:camera_config.CameraConfig.roi)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::base::IntRect* temp = _impl_.roi_;
  _impl_.roi_ = nullptr;
  return temp;
}
inline ::base::IntRect* CameraConfig::_internal_mutable_roi() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.roi_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::base::IntRect>(GetArena());
    _impl_.roi_ = reinterpret_cast<::base::IntRect*>(p);
  }
  return _impl_.roi_;
}
inline ::base::IntRect* CameraConfig::mutable_roi() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::base::IntRect* _msg = _internal_mutable_roi();
  // @@protoc_insertion_point(field_mutable:camera_config.CameraConfig.roi)
  return _msg;
}
inline void CameraConfig::set_allocated_roi(::base::IntRect* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.roi_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.roi_ = reinterpret_cast<::base::IntRect*>(value);
  // @@protoc_insertion_point(field_set_allocated:camera_config.CameraConfig.roi)
}

// optional int32 reverse_image = 12;
inline bool CameraConfig::has_reverse_image() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline void CameraConfig::clear_reverse_image() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.reverse_image_ = 0;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline ::int32_t CameraConfig::reverse_image() const {
  // @@protoc_insertion_point(field_get:camera_config.CameraConfig.reverse_image)
  return _internal_reverse_image();
}
inline void CameraConfig::set_reverse_image(::int32_t value) {
  _internal_set_reverse_image(value);
  _impl_._has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_set:camera_config.CameraConfig.reverse_image)
}
inline ::int32_t CameraConfig::_internal_reverse_image() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.reverse_image_;
}
inline void CameraConfig::_internal_set_reverse_image(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.reverse_image_ = value;
}

// int32 trigger_type = 13;
inline void CameraConfig::clear_trigger_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.trigger_type_ = 0;
}
inline ::int32_t CameraConfig::trigger_type() const {
  // @@protoc_insertion_point(field_get:camera_config.CameraConfig.trigger_type)
  return _internal_trigger_type();
}
inline void CameraConfig::set_trigger_type(::int32_t value) {
  _internal_set_trigger_type(value);
  // @@protoc_insertion_point(field_set:camera_config.CameraConfig.trigger_type)
}
inline ::int32_t CameraConfig::_internal_trigger_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.trigger_type_;
}
inline void CameraConfig::_internal_set_trigger_type(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.trigger_type_ = value;
}

// optional .camera_config.DirectoryCameraConfig virtual_folder = 14;
inline bool CameraConfig::has_virtual_folder() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.virtual_folder_ != nullptr);
  return value;
}
inline void CameraConfig::clear_virtual_folder() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.virtual_folder_ != nullptr) _impl_.virtual_folder_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const ::camera_config::DirectoryCameraConfig& CameraConfig::_internal_virtual_folder() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::camera_config::DirectoryCameraConfig* p = _impl_.virtual_folder_;
  return p != nullptr ? *p : reinterpret_cast<const ::camera_config::DirectoryCameraConfig&>(::camera_config::_DirectoryCameraConfig_default_instance_);
}
inline const ::camera_config::DirectoryCameraConfig& CameraConfig::virtual_folder() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:camera_config.CameraConfig.virtual_folder)
  return _internal_virtual_folder();
}
inline void CameraConfig::unsafe_arena_set_allocated_virtual_folder(::camera_config::DirectoryCameraConfig* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.virtual_folder_);
  }
  _impl_.virtual_folder_ = reinterpret_cast<::camera_config::DirectoryCameraConfig*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:camera_config.CameraConfig.virtual_folder)
}
inline ::camera_config::DirectoryCameraConfig* CameraConfig::release_virtual_folder() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::camera_config::DirectoryCameraConfig* released = _impl_.virtual_folder_;
  _impl_.virtual_folder_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::camera_config::DirectoryCameraConfig* CameraConfig::unsafe_arena_release_virtual_folder() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:camera_config.CameraConfig.virtual_folder)

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::camera_config::DirectoryCameraConfig* temp = _impl_.virtual_folder_;
  _impl_.virtual_folder_ = nullptr;
  return temp;
}
inline ::camera_config::DirectoryCameraConfig* CameraConfig::_internal_mutable_virtual_folder() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.virtual_folder_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::camera_config::DirectoryCameraConfig>(GetArena());
    _impl_.virtual_folder_ = reinterpret_cast<::camera_config::DirectoryCameraConfig*>(p);
  }
  return _impl_.virtual_folder_;
}
inline ::camera_config::DirectoryCameraConfig* CameraConfig::mutable_virtual_folder() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000002u;
  ::camera_config::DirectoryCameraConfig* _msg = _internal_mutable_virtual_folder();
  // @@protoc_insertion_point(field_mutable:camera_config.CameraConfig.virtual_folder)
  return _msg;
}
inline void CameraConfig::set_allocated_virtual_folder(::camera_config::DirectoryCameraConfig* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete (_impl_.virtual_folder_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = (value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }

  _impl_.virtual_folder_ = reinterpret_cast<::camera_config::DirectoryCameraConfig*>(value);
  // @@protoc_insertion_point(field_set_allocated:camera_config.CameraConfig.virtual_folder)
}

// -------------------------------------------------------------------

// DirectoryCameraConfig

// string directory = 1;
inline void DirectoryCameraConfig::clear_directory() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.directory_.ClearToEmpty();
}
inline const std::string& DirectoryCameraConfig::directory() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:camera_config.DirectoryCameraConfig.directory)
  return _internal_directory();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void DirectoryCameraConfig::set_directory(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.directory_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:camera_config.DirectoryCameraConfig.directory)
}
inline std::string* DirectoryCameraConfig::mutable_directory() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_directory();
  // @@protoc_insertion_point(field_mutable:camera_config.DirectoryCameraConfig.directory)
  return _s;
}
inline const std::string& DirectoryCameraConfig::_internal_directory() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.directory_.Get();
}
inline void DirectoryCameraConfig::_internal_set_directory(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.directory_.Set(value, GetArena());
}
inline std::string* DirectoryCameraConfig::_internal_mutable_directory() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.directory_.Mutable( GetArena());
}
inline std::string* DirectoryCameraConfig::release_directory() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:camera_config.DirectoryCameraConfig.directory)
  return _impl_.directory_.Release();
}
inline void DirectoryCameraConfig::set_allocated_directory(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.directory_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.directory_.IsDefault()) {
    _impl_.directory_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:camera_config.DirectoryCameraConfig.directory)
}

// string image_extension = 2;
inline void DirectoryCameraConfig::clear_image_extension() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.image_extension_.ClearToEmpty();
}
inline const std::string& DirectoryCameraConfig::image_extension() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:camera_config.DirectoryCameraConfig.image_extension)
  return _internal_image_extension();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void DirectoryCameraConfig::set_image_extension(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.image_extension_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:camera_config.DirectoryCameraConfig.image_extension)
}
inline std::string* DirectoryCameraConfig::mutable_image_extension() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_image_extension();
  // @@protoc_insertion_point(field_mutable:camera_config.DirectoryCameraConfig.image_extension)
  return _s;
}
inline const std::string& DirectoryCameraConfig::_internal_image_extension() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.image_extension_.Get();
}
inline void DirectoryCameraConfig::_internal_set_image_extension(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.image_extension_.Set(value, GetArena());
}
inline std::string* DirectoryCameraConfig::_internal_mutable_image_extension() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.image_extension_.Mutable( GetArena());
}
inline std::string* DirectoryCameraConfig::release_image_extension() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:camera_config.DirectoryCameraConfig.image_extension)
  return _impl_.image_extension_.Release();
}
inline void DirectoryCameraConfig::set_allocated_image_extension(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.image_extension_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.image_extension_.IsDefault()) {
    _impl_.image_extension_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:camera_config.DirectoryCameraConfig.image_extension)
}

// bool loop = 3;
inline void DirectoryCameraConfig::clear_loop() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.loop_ = false;
}
inline bool DirectoryCameraConfig::loop() const {
  // @@protoc_insertion_point(field_get:camera_config.DirectoryCameraConfig.loop)
  return _internal_loop();
}
inline void DirectoryCameraConfig::set_loop(bool value) {
  _internal_set_loop(value);
  // @@protoc_insertion_point(field_set:camera_config.DirectoryCameraConfig.loop)
}
inline bool DirectoryCameraConfig::_internal_loop() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.loop_;
}
inline void DirectoryCameraConfig::_internal_set_loop(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.loop_ = value;
}

// -------------------------------------------------------------------

// Cameras

// repeated .camera_config.CameraConfig camera_configs = 1;
inline int Cameras::_internal_camera_configs_size() const {
  return _internal_camera_configs().size();
}
inline int Cameras::camera_configs_size() const {
  return _internal_camera_configs_size();
}
inline void Cameras::clear_camera_configs() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.camera_configs_.Clear();
}
inline ::camera_config::CameraConfig* Cameras::mutable_camera_configs(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:camera_config.Cameras.camera_configs)
  return _internal_mutable_camera_configs()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::camera_config::CameraConfig>* Cameras::mutable_camera_configs()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:camera_config.Cameras.camera_configs)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_camera_configs();
}
inline const ::camera_config::CameraConfig& Cameras::camera_configs(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:camera_config.Cameras.camera_configs)
  return _internal_camera_configs().Get(index);
}
inline ::camera_config::CameraConfig* Cameras::add_camera_configs() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::camera_config::CameraConfig* _add = _internal_mutable_camera_configs()->Add();
  // @@protoc_insertion_point(field_add:camera_config.Cameras.camera_configs)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::camera_config::CameraConfig>& Cameras::camera_configs() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:camera_config.Cameras.camera_configs)
  return _internal_camera_configs();
}
inline const ::google::protobuf::RepeatedPtrField<::camera_config::CameraConfig>&
Cameras::_internal_camera_configs() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.camera_configs_;
}
inline ::google::protobuf::RepeatedPtrField<::camera_config::CameraConfig>*
Cameras::_internal_mutable_camera_configs() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.camera_configs_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace camera_config


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // camera_5fconfig_2eproto_2epb_2eh
